export const TEST_IDS = {
    JUICIEST_LINK: 'juiciest-link',
    JUICIEST_LINK_MOB: 'juiciest-link-mobile',
    VEGAN: 'vegan-cuisine',
    HEADER: 'header',
    FOOTER: 'footer',
    NAV: 'nav',
    BREADCRUMBS: 'breadcrumbs',
    HUMB_ICON: 'hamburger-icon',
    CLOSE_ICON: 'close-icon',
    SEARCH_INPUT: 'search-input',
    SEARCH_BUTTON: 'search-button',
    FOOD_CARD: 'food-card',
    CARD_LINK: 'card-link',
    CAROUSEL: 'carousel',
    CAROUSEL_CARD: 'carousel-card',
    CAROUSEL_BACK: 'carousel-back',
    CAROUSEL_FORWARD: 'carousel-forward',
    ALLERGEN_SWITCHER: 'allergens-switcher',
    ALLERGEN_BUTTON: 'allergens-menu-button',
    ALLERGEN_MENU: 'allergens-menu',
    FILTER_DRAWER: 'filter-drawer',
    CLOSE_FILTER_DRAWER: 'close-filter-drawer',
    FILTER_BUTTON: 'filter-button',
    CLEAR_FILTER_BUTTON: 'clear-filter-button',
    FIND_RECIPE_BUTTON: 'find-recipe-button',
    FILTER_CATEGORY: 'filter-menu-button-категория',
    VEGAN_CHECKBOX: 'checkbox-веганская кухня',
    ALLERGEN_SWITCHER_FILTER: 'allergens-switcher-filter',
    ALLERGEN_BUTTON_FILTER: 'allergens-menu-button-filter',
    ADD_OTHER_ALLERGEN: 'add-other-allergen',
    ADD_ALLERGEN_BUTTON: 'add-allergen-button',
    FILTER_TAG: 'filter-tag',
    ERROR_PAGE_GO_HOME: 'error-page-go-home',
    APP_LOADER: 'app-loader',
    LOADER_SEARCH_BLOCK: 'loader-search-block',
    ERROR_NOTIFICATION: 'error-notification',
    CLOSE_ALERT_BUTTON: 'close-alert-button',
    LOAD_MORE_BUTTON: 'load-more-button',
    DECREMENT_STEPPER: 'decrement-stepper',
    INCREMENT_STEPPER: 'increment-stepper',
    INGREDIENT_QUANTITY: 'ingredient-quantity',

    SIGN_IN_FORM: 'sign-in-form',
    LOGIN_INPUT: 'login-input',
    PASSWORD_INPUT: 'password-input',
    PASSWORD_VISIBILITY_BUTTON: 'password-visibility-button',
    SUBMIT_BUTTON: 'submit-button',
    SUBMIT_CODE: 'submit-code',
    FORGOT_PASSWORD: 'forgot-password',

    SIGN_IN_ERROR_MODAL: 'sign-in-error-modal',
    CLOSE_BUTTON: 'close-button',
    REPEAT_BUTTON: 'repeat-button',

    SIGN_UP_PROGRESS: 'sign-up-progress',
    SIGN_UP_FORM: 'sign-up-form',
    FIRST_NAME_INPUT: 'first-name-input',
    LAST_NAME_INPUT: 'last-name-input',
    EMAIL_INPUT: 'email-input',
    CONFIRM_PASSWORD_INPUT: 'confirm-password-input',

    SIGN_UP_SUCCESS_MODAL: 'sign-up-success-modal',

    EMAIL_VERIFICATION_FAILED_MODAL: 'email-verification-failed-modal',

    SEND_EMAIL_MODAL: 'send-email-modal',
    VERIFICATION_CODE_MODAL: 'verification-code-modal',
    VERIFICATION_CODE_INPUT: 'verification-code-input',

    RESET_CREDENTIALS_MODAL: 'reset-credentials-modal',

    RECIPE_FORM: 'recipe-form',
    RECIPE_IMAGE_BLOCK_INPUT_FILE: 'recipe-image-block-input-file',
    RECIPE_CATEGORIES: 'recipe-categories',
    RECIPE_TITLE: 'recipe-title',
    RECIPE_DESCRIPTION: 'recipe-description',
    RECIPE_PORTIONS: 'recipe-portions',
    RECIPE_TIME: 'recipe-time',

    RECIPE_INGREDIENTS_TITLE: (index: number) => `recipe-ingredients-title-${index}`,
    RECIPE_INGREDIENTS_COUNT: (index: number) => `recipe-ingredients-count-${index}`,
    RECIPE_INGREDIENTS_MEASURE_UNIT: (index: number) => `recipe-ingredients-measureUnit-${index}`,

    RECIPE_STEPS_IMAGE_BLOCK: (index: number) => `recipe-steps-image-block-${index}`,
    RECIPE_STEPS_IMAGE_BLOCK_INPUT_FILE: (index: number) =>
        `recipe-steps-image-block-${index}-input-file`,
    RECIPE_STEPS_DESCRIPTION: (index: number) => `recipe-steps-description-${index}`,

    RECIPE_SAVE_DRAFT_BUTTON: 'recipe-save-draft-button',
    RECIPE_PUBLISH_RECIPE_BUTTON: 'recipe-publish-recipe-button',

    RECIPE_INGREDIENTS_REMOVE: (index: number) => `recipe-ingredients-remove-ingredients-${index}`,
    RECIPE_INGREDIENTS_ADD: 'recipe-ingredients-add-ingredients',

    RECIPE_STEPS_IMAGE_PREVIEW_IMAGE: (index: number) =>
        `recipe-steps-image-block-${index}-preview-image`,
    RECIPE_STEPS_REMOVE_BUTTON: (index: number) => `recipe-steps-remove-button-${index}`,

    RECIPE_IMAGE_BLOCK_PREVIEW_IMAGE: 'recipe-image-block-preview-image',
    RECIPE_IMAGE_BLOCK: 'recipe-image-block',
    RECIPE_IMAGE_MODAL: 'recipe-image-modal',
    RECIPE_IMAGE_MODAL_IMAGE_BLOCK: 'recipe-image-modal-image-block',
    RECIPE_IMAGE_MODAL_PREVIEW_IMAGE: 'recipe-image-modal-preview-image',
    RECIPE_PREVENTIVE_MODAL: 'recipe-preventive-modal',
    RECIPE_DELETE_BUTTON: 'recipe-delete-button',

    HEADER_LOGO: 'header-logo',

    ADD_RECIPE_BUTTON: 'add-recipe-button',
} as const;
