export enum EndpointNames {
    GET_POSTS = 'getPosts',
    GET_RECIPES = 'getRecipes',
    GET_RECIPES_BY_CATEGORY = 'getRecipesByCategory',
    GET_RECIPE_BY_ID = 'getRecipeById',
    GET_CATEGORIES = 'getCategories',
    GET_CATEGORY_BY_ID = 'getCategoryById',
    SIGN_UP = 'signup',
    LOGIN = 'login',
    FORGOT_PASSWORD = 'forgotPassword',
    VERIFY_OTP = 'verifyOtp',
    RESET_PASSWORD = 'resetPassword',
    CREATE_RECIPE = 'createRecipe',
    GET_MEASURE_UNITS = 'measureUnits',
    UPLOAD_FILE = 'uploadFile',
    EDIT_RECIPE = 'editRecipe',
}
